services:
  db:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - rock-net
  rock-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rock-api
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mydb
      DB_USER: user
      DB_PASS: password
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - rock-net
networks:
  rock-net:
    driver: bridge
volumes:
  db_data:
    driver: local